/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package phbot;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Bot classUnderTest = new Bot();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
